### ISSUE TITLE
Help: GstObject error

### ISSUE THREAD

**Issue by filipesaraiva** [Aseman-Land/Cutegram#41]
Hello guys, I am trying to update the cutegram package on Mageia, but I am getting the follow error with 2.2.0 version:

> $ cutegram 
> 
> (cutegram:3665): GLib-GObject-WARNING **: cannot register existing type 'GstObject'
> 
> (cutegram:3665): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
> 
> (cutegram:3665): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed
> 
> (cutegram:3665): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
> 
> (cutegram:3665): GStreamer-CRITICAL **: gst_element_class_set_details_simple: assertion 'GST_IS_ELEMENT_CLASS (klass)' failed
> 
> (cutegram:3665): GStreamer-WARNING **: static caps 0x7f3fecae3650 string is NULL
> 
> (cutegram:3665): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
> 
> (cutegram:3665): GStreamer-WARNING **: static caps 0x7f3fecae35d0 string is NULL
> 
> (cutegram:3665): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
> 
> (cutegram:3665): GStreamer-WARNING **: static caps 0x7f3fecae3650 string is NULL
> 
> (cutegram:3665): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed

It is related with GStreamer but would you have some idea about what is it?

Thanks.

**Comment by realbardia** [comment]
Hi
It happened because a conflict between webkit and gstreamer. I don't know why it will not happen when cutegram build using official Qt binaries/build.
So to fix thix problem you should build Cutegram using ` DISABLE_ASEMAN_WEBGRABBER ` flag to disable webkit support. It'll disable link preview too.

    qmake -r .. PREFIX=/usr DEFINES+=DISABLE_ASEMAN_WEBGRABBER

**Comment by filipesaraiva** [comment]
Thanks @realbardia, it is working now!

**Comment by shiba89** [comment]
Compiling qtwebkit against qtmultimedia instead of gstreamer seems to solve this problem. So even if maybe it's not something up to Cutegram developers, you can find out how to do this looking at Gentoo's ebuild for qtwebkit https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-qt/qtwebkit (look what it does when gstreamer is disabled and multimedia enabled).

Warning: compiling qtwebkit takes a lot of time, thus I think you are better off just disabling the webgrabber.
