### ISSUE TITLE
Join your efforts wth tdesktop

### ISSUE THREAD

**Issue by mbnoimi** [Aseman-Land/Cutegram#67]
I suggest to join your efforts with [tdesktop](https://github.com/telegramdesktop/tdesktop) instead of forking a dead project.

I already know that tdesktop guys very slow and they don't merge requests until a while but enlarging desktop client community is in favor of the community instead of split the community between two projects,

**Comment by SanKro** [comment]
@mbnoimi tdesktop is crap. its build to be static, it patches Qt to work, development sucks because nobody cares about userequests or bugs, its unflexible and bla
if so, it would be a mucb better idea to join the telepathy-telegram crew https://akulichalexandr.wordpress.com/2015/03/24/telegram-connection-manager-the-first-release-is-going-on/
and build a unified and well documented library for telegram-Qt. stay with this client-frontend (because its awesome) and just leave that shitty official client in the corner it belongs

**Comment by mbnoimi** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    On 06/08/2015 03:57 PM, SanKro wrote:
    
    tdesktop is crap. its build to be static, it patches
      Qt to work, development sucks because nobody cares about
      userequests or bugs, its unflexible and bla
    
    This is a little bit correct but don't forget tdesktop is officcal
    client so most users will use and don't forget too. Telegram isn't
    open source! The clients are open while the server isn't so they
    dominate on the project and they can shutdown any client by changing
    their API easily. For that I consider any unofficial client is
    wasting for the community efforts (specially the maintainers) unless
    that client find out a solution without need to connect to Telegram
    LLP servers or Telegram LLP opened the source of their server.
    
    -- 
Best Regards,
Muhammad Bashir Al-Noimi
Skype+Telegram+GMail: mbnoimi

**Comment by realbardia** [comment]
Yes. SanKro Right. But there is also another reasons.
Cutegram and Cutegram's roles is different from tdesktop. for example Cutegram uses QML instead of normal painting engine.
Surely community needs different apps with different targets. Some users like a lightweight client like tdesktop, Some other like a telegram client with modern UI. Some users like twitter emojis, some other likes apple emojies and ...

Also Cutegram uses libqtelegram. Community needs libraries like libqtelegram and Cutegram helps libqtelegram to be alive. It's an ecosystem.

But I accept your words about close source server. Yes, They're close source and It might they block thirdparty apps in the future.
But There is our only way currently and We're trying to keep cutegram alive.

**Comment by Kaffeine** [comment]
Just to say, I would support the idea to rebase the on TelegramQt :).
But I have to note, that TelegramQt is a high-level library, which hides protocol details behind (convenient) API, which can't be designed quickly. And I have less implemented features, than libqtelegram. I have a suggestion to develop libqtelegram, but I have a reasons to continue TelegramQt. You can read it at https://akulichalexandr.wordpress.com/2015/03/24/telegram-connection-manager-the-first-release-is-going-on/comment-page-1/#comment-72 .
